name: Deploy to Google Cloud Run

on:
  push:
    branches: [ gcloud ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    env:
      SERVICE: openwebui
      REPO: openwebui-repo
      IMAGE: openwebui
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Print secrets directly
        run: |
          echo "GCP_PROJECT=${{ secrets.GCP_PROJECT }}"
          echo "GCP_REGION=${{ secrets.GCP_REGION }}"

      - name: Set up Cloud SDK
        uses: google-github-actions/setup-gcloud@v2
        with:
          project_id: ${{ secrets.GCP_PROJECT }}
          service_account_key: ${{ secrets.GCP_SA_KEY }}
          export_default_credentials: true

      - name: Print GCP service account key (redact before sharing logs!)
        run: echo "${{ secrets.GCP_SA_KEY }}"

      - name: Configure Docker for Artifact Registry
        run: gcloud auth configure-docker us-central1-docker.pkg.dev

      - name: Print gcloud auth info
        run: gcloud auth list

      - name: Print gcloud config
        run: gcloud config list

      - name: Whoami
        run: gcloud info --format='get(config.account)'

      - name: List Artifact Registry repos
        run: gcloud artifacts repositories list --project=${{ secrets.GCP_PROJECT }} --location=${{ secrets.GCP_REGION }}

      - name: Build Docker image
        run: |
          docker build -f Dockerfile --tag us-central1-docker.pkg.dev/${{ secrets.GCP_PROJECT }}/${{ env.REPO }}/${{ env.IMAGE }}:${{ github.sha }} .

      - name: Push Docker image
        run: |
          docker push us-central1-docker.pkg.dev/${{ secrets.GCP_PROJECT }}/${{ env.REPO }}/${{ env.IMAGE }}:${{ github.sha }}

      - name: Deploy to Cloud Run
        run: |
          gcloud run deploy ${{ env.SERVICE }} \
            --image=us-central1-docker.pkg.dev/${{ secrets.GCP_PROJECT }}/${{ env.REPO }}/${{ env.IMAGE }}:${{ github.sha }} \
            --region=${{ secrets.GCP_REGION }} \
            --platform=managed \
            --allow-unauthenticated 